name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '2.x'

            - name: Install dependencies
              run: flutter pub get

            - name: Build web bundle
              run: flutter build web

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                name: web-bundle
                path: build/web
